<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('permissions')->insert([
                [
                    'id'                => 1,
                    'name'              => 'request_tray',
                    'display_name'      => 'Solicitudes',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 2,
                    'name'              => 'request_authorization_tray',
                    'display_name'      => 'Autorización de solicitudes',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 3,
                    'name'              => 'impediments_response_tray',
                    'display_name'      => 'Respuesta de Impedimentos',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 4,
                    'name'              => 'high_validation_tray',
                    'display_name'      => 'Validación de altas',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 5,
                    'name'              => 'low_validation_tray',
                    'display_name'      => 'Validación de bajas',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 7,
                    'name'              => 'impediment_query',
                    'display_name'      => 'Consulta de impedimentos',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                 [
                    'id'                => 8,
                    'name'              => 'module_query',
                    'display_name'      => 'Consulta del módulo',
                    'description'       => null,
                    'parent_id'         => 7,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 9,
                    'name'              => 'user_management',
                    'display_name'      => 'Administración de usuarios',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 10,
                    'name'              => 'authorization_inbox_impediment_clearance',
                    'display_name'      => 'Autorización de alta de impedimentos',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 11,
                    'name'              => 'disability_discharge_authorization_tray',
                    'display_name'      => 'Autorización de baja de impedimentos',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 12,
                    'name'              => 'catalog_management',
                    'display_name'      => 'Administración de catálogos',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 13,
                    'name'              => 'logbook',
                    'display_name'      => 'Bitácora',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 14,
                    'name'              => 'reports',
                    'display_name'      => 'Reportes',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 15,
                    'name'              => 'request_log',
                    'display_name'      => 'Bitácora Solicitudes',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 16,
                    'name'              => 'impediment_log',
                    'display_name'      => 'Bitácora Impedimentos',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 17,
                    'name'              => 'validate_inbox_impediment_modify',
                    'display_name'      => 'Validación de alta de modificación',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 19,
                    'name'              => 'verification_inbox',
                    'display_name'      => 'Verificaciones',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 20,
                    'name'              => 'work_assignation_inbox',
                    'display_name'      => 'Asignación de trabajo',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 21,
                    'name'              => 'impediment_query_modify',
                    'display_name'      => 'Modificación de impedimento',
                    'description'       => null,
                    'parent_id'         => 7,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 22,
                    'name'              => 'impediment_query_correction',
                    'display_name'      => 'Corrección de impedimento',
                    'description'       => null,
                    'parent_id'         => 7,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 23,
                    'name'              => 'impediment_query_reactive',
                    'display_name'      => 'Reactivar impedimento',
                    'description'       => null,
                    'parent_id'         => 7,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 24,
                    'name'              => 'impediment_query_delete',
                    'display_name'      => 'Eliminar impedimento',
                    'description'       => null,
                    'parent_id'         => 7,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],
                [
                    'id'                => 25,
                    'name'              => 'request_authorization_rejection_tray',
                    'display_name'      => 'Autorizacion de rechazos',
                    'description'       => null,
                    'parent_id'         => null,
                    'unassignable'      => false,
                    'created_at'        => Carbon::now(),
                    'updated_at'        => Carbon::now(),
                ],

            ]);
    }
}
