<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserPermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('user_permission')->insert([
                [
                    'id_usuario'    => '1',
                    'id_permission' => '1',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '2',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '3',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '4',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '5',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '7',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '8',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '9',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '10',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '11',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '12',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '13',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '14',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '15',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '16',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '17',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '19',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '1',
                    'id_permission' => '20',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '1',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '2',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '3',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '4',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '5',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '7',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '8',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '9',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '10',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '11',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '12',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '13',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '14',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '15',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '16',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '17',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '19',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '2',
                    'id_permission' => '20',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                //---------
                 [
                    'id_usuario'    => '3',
                    'id_permission' => '1',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '2',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '3',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '4',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '5',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '7',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '8',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '9',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '10',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '11',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '12',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '13',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '14',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '15',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '16',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '17',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '19',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '3',
                    'id_permission' => '20',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '1',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '2',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '3',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '4',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '5',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '7',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '8',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '9',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '10',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '11',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '12',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '13',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '14',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '15',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '16',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '17',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '19',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '4',
                    'id_permission' => '20',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '1',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '2',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '3',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '4',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '5',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '7',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '8',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '9',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '10',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '11',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '12',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '13',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '14',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '15',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '16',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '17',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '19',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '5',
                    'id_permission' => '20',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '1',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '2',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '3',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '4',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '5',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '7',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '8',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '9',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '10',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '11',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '12',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '13',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '14',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '15',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '16',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '17',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '19',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '6',
                    'id_permission' => '20',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '1',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '2',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '3',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '4',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '5',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '7',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '8',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '9',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '10',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '11',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '12',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '13',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '14',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '15',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '16',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '17',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '19',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '7',
                    'id_permission' => '20',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '1',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '2',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '3',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '4',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '5',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '7',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '8',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '9',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '10',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '11',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '12',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '13',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '14',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '15',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '16',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '17',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '19',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '8',
                    'id_permission' => '20',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '1',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '2',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '3',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '4',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '5',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '7',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '8',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '9',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '10',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '11',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '12',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '13',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '14',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '15',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '16',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '17',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '19',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
                [
                    'id_usuario'    => '9',
                    'id_permission' => '20',
                    'created_at'    => Carbon::now(),
                    'updated_at'    => Carbon::now(),
                ],
            ]);
    }
}
