# Image of project
FROM ubuntu:22.04

# Arguments
ARG WWWGROUP
ARG TIMEZONE

# Environment variables
ENV DEBIAN_FRONTEND noninteractive
ENV PHP_VERSION=8.2
ENV NODE_VERSION=20
ENV USER_GROUP=devgroup
ENV USER_NAME=devuser
ENV SUPERVISOR_PHP_USER=${USER_NAME}
ENV TZ=${TIMEZONE}

# Set timezone
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

# Update package list and make keyrings directory
RUN apt-get update && mkdir -p /etc/apt/keyrings

# Install system dependencies
RUN apt-get install -y \
    gnupg \
    gosu \
    curl \
    wget \
    ca-certificates \
    zip \
    unzip \
    git \
    supervisor \
    sqlite3 \
    libcap2-bin \
    libpng-dev \
    python2 \
    dnsutils \
    librsvg2-bin \
    fswatch \
    ffmpeg \
    nano \
    apt-transport-https \
    software-properties-common \
    libpq-dev \
    libldap2-dev \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libmcrypt-dev \
    libcurl4-openssl-dev \
    cron

RUN add-apt-repository ppa:ondrej/php \
    && apt-get update \
    && apt-get install -y php${PHP_VERSION}

# Install PHP extensions
RUN apt-get install -y \
    php${PHP_VERSION}-cli \
    php${PHP_VERSION}-common \
    php${PHP_VERSION}-dev \
    php${PHP_VERSION}-pgsql \
    php${PHP_VERSION}-sqlite3 \
    php${PHP_VERSION}-gd \
    php${PHP_VERSION}-curl \
    php${PHP_VERSION}-imap \
    php${PHP_VERSION}-mysql \
    php${PHP_VERSION}-mbstring \
    php${PHP_VERSION}-xml \
    php${PHP_VERSION}-zip \
    php${PHP_VERSION}-zip \
    php${PHP_VERSION}-bcmath \
    php${PHP_VERSION}-soap \
    php${PHP_VERSION}-intl \
    php${PHP_VERSION}-readline \
    php${PHP_VERSION}-ldap \
    php${PHP_VERSION}-msgpack \
    php${PHP_VERSION}-igbinary \
    php${PHP_VERSION}-redis \
    php${PHP_VERSION}-swoole \
    php${PHP_VERSION}-memcached \
    php${PHP_VERSION}-pcov \
    php${PHP_VERSION}-imagick \
    php${PHP_VERSION}-mcrypt \
    php${PHP_VERSION}-exif \
    php${PHP_VERSION}-xdebug

 # Install apache
 RUN apt-get install -y apache2 \
    apache2-utils \
    libapache2-mod-php${PHP_VERSION}

# Enable apache modules
RUN a2enmod rewrite headers expires

# Install database clients
RUN apt-get install -y \
    mysql-client \
    postgresql-client

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_VERSION}.x nodistro main" > /etc/apt/sources.list.d/nodesource.list \
    && apt-get update \
    && apt-get install -y nodejs \
    && npm install -g npm

# Clean
RUN apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Capabilities
RUN setcap "cap_net_bind_service=+ep" /usr/bin/php${PHP_VERSION}

# Create user and group
RUN groupadd --force -g ${WWWGROUP} ${USER_GROUP}
RUN useradd -ms /bin/bash --no-user-group -g ${WWWGROUP} -u 1337 ${USER_NAME}

# Set working directory
WORKDIR /var/www

# Start script
COPY start-container /usr/local/bin/start-container
RUN chmod +x /usr/local/bin/start-container

# Init script
ENTRYPOINT ["start-container"]
