INSERT INTO im_cat_entidad_federativa VALUES (228, 'Baja California', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (229, 'Baja California Sur', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (230, 'Campeche', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (241, 'Estado de México', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (248, 'Querétaro', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (236, 'Durango', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (237, 'Guanajuato', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (239, 'Hidalgo', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (240, 'Jalisco', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (243, 'Morelos', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (244, 'Nayarit', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (247, 'Puebla', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (249, 'Quintana Roo', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (251, 'Sinaloa', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (253, 'Tabasco', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (254, 'Tamaulipas', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (255, 'Tlaxcala', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (258, 'Zacatecas', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (233, 'Coahuila de Zaragoza', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (245, 'Nuevo León', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (250, 'San Luis Potosí', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (257, 'Yucatán', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (227, 'Aguascalientes', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (231, 'Chiapas', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (232, 'Chihuahua', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (235, 'Ciudad de México', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (234, 'Colima', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (238, 'Guerrero', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (242, 'Michoacán de Ocampo', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (246, 'Oaxaca', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (252, 'Sonora', 142, false, default, null, CURRENT_TIMESTAMP, null);
INSERT INTO im_cat_entidad_federativa VALUES (256, 'Veracruz de Ignacio de la Llave', 142, false, default, null, CURRENT_TIMESTAMP, null);
