insert into im_cat_pais  VALUES
   (1, 'AF', 'AFG', 'Afganistán', false, default, null, CURRENT_TIMESTAMP, null)
,  (2, 'AL', 'ALB', 'Albania', false, default, null, CURRENT_TIMESTAMP, null)
,  (3, 'DZ', 'DZA', 'Argelia', false, default, null, CURRENT_TIMESTAMP, null)
,  (4, 'AS', 'ASM', 'Samoa (Americana)', false, default, null, CURRENT_TIMESTAMP, null)
,  (5, 'AD', 'AND', 'Andorra', false, default, null, CURRENT_TIMESTAMP, null)
,  (6, 'AO', 'AGO', 'Angola', false, default, null, CURRENT_TIMESTAMP, null)
,  (7, 'AI', 'AIA', 'Anguilla', false, default, null, CURRENT_TIMESTAMP, null)
,  (8, 'AQ', 'ATA', 'Antártida', false, default, null, CURRENT_TIMESTAMP, null)
,  (9, 'AG', 'ATG', 'Antigua y Barbuda', false, default, null, CURRENT_TIMESTAMP, null)
,  (10, 'AR', 'ARG', 'Argentina', false, default, null, CURRENT_TIMESTAMP, null)
,  (11, 'AM', 'ARM', 'Armenia', false, default, null, CURRENT_TIMESTAMP, null)
,  (12, 'AW', 'ABW', 'Aruba', false, default, null, CURRENT_TIMESTAMP, null)
,  (13, 'AU', 'AUS', 'Australia', false, default, null, CURRENT_TIMESTAMP, null)
,  (14, 'AT', 'AUT', 'Austria', false, default, null, CURRENT_TIMESTAMP, null)
,  (15, 'AZ', 'AZE', 'Azerbaiján', false, default, null, CURRENT_TIMESTAMP, null)
,  (16, 'BS', 'BHS', 'Bahamas', false, default, null, CURRENT_TIMESTAMP, null)
,  (17, 'BH', 'BHR', 'Bahrein', false, default, null, CURRENT_TIMESTAMP, null)
,  (18, 'BD', 'BGD', 'Bangladesh', false, default, null, CURRENT_TIMESTAMP, null)
,  (19, 'BB', 'BRB', 'Barbados', false, default, null, CURRENT_TIMESTAMP, null)
,  (20, 'BY', 'BLR', 'Bielorrusia', false, default, null, CURRENT_TIMESTAMP, null)
,  (21, 'BE', 'BEL', 'Bélgica', false, default, null, CURRENT_TIMESTAMP, null)
,  (22, 'BZ', 'BLZ', 'Belice', false, default, null, CURRENT_TIMESTAMP, null)
,  (23, 'BJ', 'BEN', 'Benín', false, default, null, CURRENT_TIMESTAMP, null)
,  (24, 'BM', 'BMU', 'Bermuda', false, default, null, CURRENT_TIMESTAMP, null)
,  (25, 'BT', 'BTN', 'Bhután', false, default, null, CURRENT_TIMESTAMP, null)
,  (26, 'BO', 'BOL', 'Bolivia', false, default, null, CURRENT_TIMESTAMP, null)
,  (27, 'BA', 'BIH', 'Bosnia - Herzegovina', false, default, null, CURRENT_TIMESTAMP, null)
,  (28, 'BW', 'BWA', 'Botswana', false, default, null, CURRENT_TIMESTAMP, null)
,  (29, 'BV', 'BVT', 'Isla Bouvet', false, default, null, CURRENT_TIMESTAMP, null)
,  (30, 'BR', 'BRA', 'Brasil', false, default, null, CURRENT_TIMESTAMP, null)
,  (31, 'IO', 'IOT', 'Territorio Britanico Del Ocean', false, default, null, CURRENT_TIMESTAMP, null)
,  (32, 'BN', 'BRN', 'Brunéi', false, default, null, CURRENT_TIMESTAMP, null)
,  (33, 'BG', 'BGR', 'Bulgaria', false, default, null, CURRENT_TIMESTAMP, null)
,  (34, 'BF', 'BFA', 'Burkina Faso', false, default, null, CURRENT_TIMESTAMP, null)
,  (35, 'BI', 'BDI', 'Burundi', false, default, null, CURRENT_TIMESTAMP, null)
,  (36, 'KH', 'KHM', 'Camboya', false, default, null, CURRENT_TIMESTAMP, null)
,  (37, 'CM', 'CMR', 'Camerún', false, default, null, CURRENT_TIMESTAMP, null)
,  (38, 'CA', 'CAN', 'Canadá', false, default, null, CURRENT_TIMESTAMP, null)
,  (39, 'CV', 'CPV', 'Cabo Verde', false, default, null, CURRENT_TIMESTAMP, null)
,  (40, 'KY', 'CYM', 'Islas Cayman', false, default, null, CURRENT_TIMESTAMP, null)
,  (41, 'CF', 'CAF', 'Rep. Centro Africana', false, default, null, CURRENT_TIMESTAMP, null)
,  (42, 'TD', 'TCD', 'Chad', false, default, null, CURRENT_TIMESTAMP, null)
,  (43, 'CL', 'CHL', 'Chile', false, default, null, CURRENT_TIMESTAMP, null)
,  (44, 'CN', 'CHN', 'China', false, default, null, CURRENT_TIMESTAMP, null)
,  (45, 'CX', 'CXR', 'Isla Christmas', false, default, null, CURRENT_TIMESTAMP, null)
,  (46, 'CC', 'CCK', 'Islas Cocos', false, default, null, CURRENT_TIMESTAMP, null)
,  (47, 'CO', 'COL', 'Colombia', false, default, null, CURRENT_TIMESTAMP, null)
,  (48, 'KM', 'COM', 'Comoras', false, default, null, CURRENT_TIMESTAMP, null)
,  (49, 'CG', 'COG', 'Congo (Rep.)', false, default, null, CURRENT_TIMESTAMP, null)
,  (50, 'CD', 'COD', 'Rep Dem Del Congo', false, default, null, CURRENT_TIMESTAMP, null)
,  (51, 'CK', 'COK', 'Islas Cook', false, default, null, CURRENT_TIMESTAMP, null)
,  (52, 'CR', 'CRI', 'Costa Rica', false, default, null, CURRENT_TIMESTAMP, null)
,  (53, 'CI', 'CIV', 'Costa de Marfil', false, default, null, CURRENT_TIMESTAMP, null)
,  (54, 'HR', 'HRV', 'Croacia', false, default, null, CURRENT_TIMESTAMP, null)
,  (55, 'CU', 'CUB', 'Cuba', false, default, null, CURRENT_TIMESTAMP, null)
,  (56, 'CY', 'CYP', 'Chipre', false, default, null, CURRENT_TIMESTAMP, null)
,  (57, 'CZ', 'CZE', 'República Checa', false, default, null, CURRENT_TIMESTAMP, null)
,  (58, 'DK', 'DNK', 'Dinamarca', false, default, null, CURRENT_TIMESTAMP, null)
,  (59, 'DJ', 'DJI', 'Yibuti', false, default, null, CURRENT_TIMESTAMP, null)
,  (60, 'DM', 'DMA', 'Dominica', false, default, null, CURRENT_TIMESTAMP, null)
,  (61, 'DO', 'DOM', 'República Dominicana', false, default, null, CURRENT_TIMESTAMP, null)
,  (62, 'TP', 'TLS', 'Timor Oriental', false, default, null, CURRENT_TIMESTAMP, null)
,  (63, 'EC', 'ECU', 'Ecuador', false, default, null, CURRENT_TIMESTAMP, null)
,  (64, 'EG', 'EGY', 'Egipto', false, default, null, CURRENT_TIMESTAMP, null)
,  (65, 'SV', 'SLV', 'El Salvador', false, default, null, CURRENT_TIMESTAMP, null)
,  (66, 'GQ', 'GNQ', 'Guinea Ecuatorial', false, default, null, CURRENT_TIMESTAMP, null)
,  (67, 'ER', 'ERI', 'Eritrea', false, default, null, CURRENT_TIMESTAMP, null)
,  (68, 'EE', 'EST', 'Estonia', false, default, null, CURRENT_TIMESTAMP, null)
,  (69, 'ET', 'ETH', 'Etiopía', false, default, null, CURRENT_TIMESTAMP, null)
,  (71, 'FK', 'FLK', 'Islas Falkland (Malvinas)', false, default, null, CURRENT_TIMESTAMP, null)
,  (72, 'FO', 'FRO', 'Islas Feroe', false, default, null, CURRENT_TIMESTAMP, null)
,  (73, 'FJ', 'FJI', 'Fiji', false, default, null, CURRENT_TIMESTAMP, null)
,  (74, 'FI', 'FIN', 'Finlandia', false, default, null, CURRENT_TIMESTAMP, null)
,  (75, 'FR', 'FRA', 'Francia', false, default, null, CURRENT_TIMESTAMP, null)
,  (76, 'GF', 'GUF', 'Guyana Francesa', false, default, null, CURRENT_TIMESTAMP, null)
,  (77, 'PF', 'PYF', 'Polinesia Francesa', false, default, null, CURRENT_TIMESTAMP, null)
,  (78, 'TF', 'ATF', 'Territorios Franceses Del Sur', false, default, null, CURRENT_TIMESTAMP, null)
,  (79, 'GA', 'GAB', 'Gabón', false, default, null, CURRENT_TIMESTAMP, null)
,  (80, 'GM', 'GMB', 'Gambia', false, default, null, CURRENT_TIMESTAMP, null)
,  (81, 'GE', 'GEO', 'Georgia', false, default, null, CURRENT_TIMESTAMP, null)
,  (82, 'DE', 'DEU', 'Alemania', false, default, null, CURRENT_TIMESTAMP, null)
,  (83, 'GH', 'GHA', 'Ghana', false, default, null, CURRENT_TIMESTAMP, null)
,  (84, 'GI', 'GIB', 'Gibraltar', false, default, null, CURRENT_TIMESTAMP, null)
,  (85, 'GR', 'GRC', 'Grecia', false, default, null, CURRENT_TIMESTAMP, null)
,  (86, 'GL', 'GRL', 'Groenlandia', false, default, null, CURRENT_TIMESTAMP, null)
,  (87, 'GD', 'GRD', 'Granada', false, default, null, CURRENT_TIMESTAMP, null)
,  (88, 'GP', 'GLP', 'Guadalupe', false, default, null, CURRENT_TIMESTAMP, null)
,  (89, 'GU', 'GUM', 'Guam', false, default, null, CURRENT_TIMESTAMP, null)
,  (90, 'GT', 'GTM', 'Guatemala', false, default, null, CURRENT_TIMESTAMP, null)
,  (91, 'GG', 'GGY', 'Guernsey', false, default, null, CURRENT_TIMESTAMP, null)
,  (92, 'GN', 'GIN', 'Guinea', false, default, null, CURRENT_TIMESTAMP, null)
,  (93, 'GW', 'GNB', 'Guinea-Bissau', false, default, null, CURRENT_TIMESTAMP, null)
,  (94, 'GY', 'GUY', 'Guyana', false, default, null, CURRENT_TIMESTAMP, null)
,  (95, 'HT', 'HTI', 'Haití', false, default, null, CURRENT_TIMESTAMP, null)
,  (96, 'HM', 'HMD', 'Isla Heard - Islas Mcdonald', false, default, null, CURRENT_TIMESTAMP, null)
,  (97, 'HN', 'HND', 'Honduras', false, default, null, CURRENT_TIMESTAMP, null)
,  (98, 'HK', 'HKG', 'Hong kong', false, default, null, CURRENT_TIMESTAMP, null)
,  (99, 'HU', 'HUN', 'Hungría', false, default, null, CURRENT_TIMESTAMP, null)
,  (100, 'IS', 'ISL', 'Islandia', false, default, null, CURRENT_TIMESTAMP, null)
,  (101, 'IN', 'IND', 'India', false, default, null, CURRENT_TIMESTAMP, null)
,  (102, 'ID', 'IDN', 'Indonesia', false, default, null, CURRENT_TIMESTAMP, null)
,  (103, 'IR', 'IRN', 'Irán', false, default, null, CURRENT_TIMESTAMP, null)
,  (104, 'IQ', 'IRQ', 'Iraq', false, default, null, CURRENT_TIMESTAMP, null)
,  (105, 'IE', 'IRL', 'Irlanda', false, default, null, CURRENT_TIMESTAMP, null)
,  (106, 'IL', 'ISR', 'Israel', false, default, null, CURRENT_TIMESTAMP, null)
,  (107, 'IT', 'ITA', 'Italia', false, default, null, CURRENT_TIMESTAMP, null)
,  (108, 'JM', 'JAM', 'Jamaica', false, default, null, CURRENT_TIMESTAMP, null)
,  (109, 'JP', 'JPN', 'Japón', false, default, null, CURRENT_TIMESTAMP, null)
,  (110, 'JE', 'JEY', 'Jersey', false, default, null, CURRENT_TIMESTAMP, null)
,  (111, 'JO', 'JOR', 'Jordania', false, default, null, CURRENT_TIMESTAMP, null)
,  (112, 'KZ', 'KAZ', 'Kazajistán', false, default, null, CURRENT_TIMESTAMP, null)
,  (113, 'KE', 'KEN', 'Kenia', false, default, null, CURRENT_TIMESTAMP, null)
,  (114, 'KI', 'KIR', 'Kiribati', false, default, null, CURRENT_TIMESTAMP, null)
,  (115, 'KP', 'PRK', 'Corea (Norte)', false, default, null, CURRENT_TIMESTAMP, null)
,  (116, 'KR', 'KOR', 'Corea del Sur', false, default, null, CURRENT_TIMESTAMP, null)
,  (117, 'KW', 'KWT', 'Kuwait', false, default, null, CURRENT_TIMESTAMP, null)
,  (118, 'KG', 'KGZ', 'Kirguizstán', false, default, null, CURRENT_TIMESTAMP, null)
,  (119, 'LA', 'LAO', 'Laos', false, default, null, CURRENT_TIMESTAMP, null)
,  (120, 'LV', 'LVA', 'Letonia', false, default, null, CURRENT_TIMESTAMP, null)
,  (121, 'LB', 'LBN', 'Líbano', false, default, null, CURRENT_TIMESTAMP, null)
,  (122, 'LS', 'LSO', 'Lesotho', false, default, null, CURRENT_TIMESTAMP, null)
,  (123, 'LR', 'LBR', 'Liberia', false, default, null, CURRENT_TIMESTAMP, null)
,  (124, 'LY', 'LBY', 'Libia', false, default, null, CURRENT_TIMESTAMP, null)
,  (125, 'LI', 'LIE', 'Liechtenstein', false, default, null, CURRENT_TIMESTAMP, null)
,  (126, 'LT', 'LTU', 'Lituania', false, default, null, CURRENT_TIMESTAMP, null)
,  (127, 'LU', 'LUX', 'Luxemburgo', false, default, null, CURRENT_TIMESTAMP, null)
,  (128, 'MO', 'MAC', 'Macao', false, default, null, CURRENT_TIMESTAMP, null)
,  (129, 'MK', 'MKD', 'Macedonia', false, default, null, CURRENT_TIMESTAMP, null)
,  (130, 'MG', 'MDG', 'Madagascar', false, default, null, CURRENT_TIMESTAMP, null)
,  (131, 'MW', 'MWI', 'Malawi', false, default, null, CURRENT_TIMESTAMP, null)
,  (132, 'MY', 'MYS', 'Malasia', false, default, null, CURRENT_TIMESTAMP, null)
,  (133, 'MV', 'MDV', 'Maldivas', false, default, null, CURRENT_TIMESTAMP, null)
,  (134, 'ML', 'MLI', 'Malí', false, default, null, CURRENT_TIMESTAMP, null)
,  (135, 'MT', 'MLT', 'Malta', false, default, null, CURRENT_TIMESTAMP, null)
,  (136, 'IM', 'IMN', 'Isla de Man', false, default, null, CURRENT_TIMESTAMP, null)
,  (137, 'MH', 'MHL', 'Islas Marshall', false, default, null, CURRENT_TIMESTAMP, null)
,  (138, 'MQ', 'MTQ', 'Martinica', false, default, null, CURRENT_TIMESTAMP, null)
,  (139, 'MR', 'MRT', 'Mauritania', false, default, null, CURRENT_TIMESTAMP, null)
,  (140, 'MU', 'MUS', 'Mauricio', false, default, null, CURRENT_TIMESTAMP, null)
,  (141, 'YT', 'MYT', 'Mayotte', false, default, null, CURRENT_TIMESTAMP, null)
,  (142, 'MX', 'MEX', 'México', false, default, null, CURRENT_TIMESTAMP, null)
,  (143, 'FM', 'FSM', 'Micronesia', false, default, null, CURRENT_TIMESTAMP, null)
,  (144, 'MD', 'MDA', 'Moldavia', false, default, null, CURRENT_TIMESTAMP, null)
,  (145, 'MC', 'MCO', 'Mónaco', false, default, null, CURRENT_TIMESTAMP, null)
,  (146, 'MN', 'MNG', 'Mongolia', false, default, null, CURRENT_TIMESTAMP, null)
,  (147, 'MS', 'MSR', 'Montserrat', false, default, null, CURRENT_TIMESTAMP, null)
,  (148, 'MA', 'MAR', 'Marruecos', false, default, null, CURRENT_TIMESTAMP, null)
,  (149, 'MZ', 'MOZ', 'Mozambique', false, default, null, CURRENT_TIMESTAMP, null)
,  (150, 'MM', 'MMR', 'Myanmar (Birmania)', false, default, null, CURRENT_TIMESTAMP, null)
,  (151, 'NA', 'NAM', 'Namibia', false, default, null, CURRENT_TIMESTAMP, null)
,  (152, 'NR', 'NRU', 'Nauru', false, default, null, CURRENT_TIMESTAMP, null)
,  (153, 'NP', 'NPL', 'Nepal', false, default, null, CURRENT_TIMESTAMP, null)
,  (154, 'AN', 'ANT', 'Antillas Holandesas', false, default, null, CURRENT_TIMESTAMP, null)
,  (155, 'NL', 'NLD', 'Países Bajos', false, default, null, CURRENT_TIMESTAMP, null)
,  (156, 'NC', 'NCL', 'Nueva Caledonia', false, default, null, CURRENT_TIMESTAMP, null)
,  (157, 'NZ', 'NZL', 'Nueva Zelanda', false, default, null, CURRENT_TIMESTAMP, null)
,  (158, 'NI', 'NIC', 'Nicaragua', false, default, null, CURRENT_TIMESTAMP, null)
,  (159, 'NE', 'NER', 'Níger', false, default, null, CURRENT_TIMESTAMP, null)
,  (160, 'NG', 'NGA', 'Nigeria', false, default, null, CURRENT_TIMESTAMP, null)
,  (161, 'NU', 'NIU', 'Niue', false, default, null, CURRENT_TIMESTAMP, null)
,  (162, 'NF', 'NFK', 'Isla Norfolk', false, default, null, CURRENT_TIMESTAMP, null)
,  (163, 'MP', 'MNP', 'Islas Marianas', false, default, null, CURRENT_TIMESTAMP, null)
,  (164, 'NO', 'NOR', 'Noruega', false, default, null, CURRENT_TIMESTAMP, null)
,  (165, 'OM', 'OMN', 'Omán', false, default, null, CURRENT_TIMESTAMP, null)
,  (166, 'PK', 'PAK', 'Pakistán', false, default, null, CURRENT_TIMESTAMP, null)
,  (167, 'PW', 'PLW', 'Palaos', false, default, null, CURRENT_TIMESTAMP, null)
,  (168, 'PS', 'PSE', 'Estado De Palestina', false, default, null, CURRENT_TIMESTAMP, null)
,  (169, 'PA', 'PAN', 'Panamá', false, default, null, CURRENT_TIMESTAMP, null)
,  (170, 'PG', 'PNG', 'Papúa Nueva Guinea', false, default, null, CURRENT_TIMESTAMP, null)
,  (171, 'PY', 'PRY', 'Paraguay', false, default, null, CURRENT_TIMESTAMP, null)
,  (172, 'PE', 'PER', 'Perú', false, default, null, CURRENT_TIMESTAMP, null)
,  (173, 'PH', 'PHL', 'Filipinas', false, default, null, CURRENT_TIMESTAMP, null)
,  (174, 'PN', 'PCN', 'Pitcairn', false, default, null, CURRENT_TIMESTAMP, null)
,  (175, 'PL', 'POL', 'Polonia', false, default, null, CURRENT_TIMESTAMP, null)
,  (176, 'PT', 'PRT', 'Portugal', false, default, null, CURRENT_TIMESTAMP, null)
,  (177, 'PR', 'PRI', 'Puerto Rico', false, default, null, CURRENT_TIMESTAMP, null)
,  (178, 'QA', 'QAT', 'Qatar', false, default, null, CURRENT_TIMESTAMP, null)
,  (179, 'RE', 'REU', 'Reunión', false, default, null, CURRENT_TIMESTAMP, null)
,  (180, 'RO', 'ROU', 'Rumanía', false, default, null, CURRENT_TIMESTAMP, null)
,  (181, 'RU', 'RUS', 'Rusia', false, default, null, CURRENT_TIMESTAMP, null)
,  (182, 'RW', 'RWA', 'Ruanda', false, default, null, CURRENT_TIMESTAMP, null)
,  (183, 'SH', 'SHN', 'Santa Elena', false, default, null, CURRENT_TIMESTAMP, null)
,  (184, 'KN', 'KNA', 'San Cristóbal y Nieves', false, default, null, CURRENT_TIMESTAMP, null)
,  (185, 'LC', 'LCA', 'Santa Lucía', false, default, null, CURRENT_TIMESTAMP, null)
,  (186, 'PM', 'SPM', 'St Pierre - Miquelon', false, default, null, CURRENT_TIMESTAMP, null)
,  (187, 'VC', 'VCT', 'San Vicente y las Granadinas', false, default, null, CURRENT_TIMESTAMP, null)
,  (188, 'WS', 'WSM', 'Samoa (Oeste)', false, default, null, CURRENT_TIMESTAMP, null)
,  (189, 'SM', 'SMR', 'San Marino', false, default, null, CURRENT_TIMESTAMP, null)
,  (190, 'ST', 'STP', 'Santo Tomé - Principe', false, default, null, CURRENT_TIMESTAMP, null)
,  (191, 'SA', 'SAU', 'Arabia Saudíta', false, default, null, CURRENT_TIMESTAMP, null)
,  (192, 'SN', 'SEN', 'Senegal', false, default, null, CURRENT_TIMESTAMP, null)
,  (193, 'RS', 'SRB', 'Serbia', false, default, null, CURRENT_TIMESTAMP, null)
,  (194, 'SC', 'SYC', 'Seychelles', false, default, null, CURRENT_TIMESTAMP, null)
,  (195, 'SL', 'SLE', 'Sierra Leona', false, default, null, CURRENT_TIMESTAMP, null)
,  (196, 'SG', 'SGP', 'Singapur', false, default, null, CURRENT_TIMESTAMP, null)
,  (197, 'SK', 'SVK', 'Eslovaquia', false, default, null, CURRENT_TIMESTAMP, null)
,  (198, 'SI', 'SVN', 'Eslovenia', false, default, null, CURRENT_TIMESTAMP, null)
,  (200, 'SB', 'SLB', 'Islas Salomón', false, default, null, CURRENT_TIMESTAMP, null)
,  (201, 'SO', 'SOM', 'Somalia', false, default, null, CURRENT_TIMESTAMP, null)
,  (202, 'ZA', 'ZAF', 'Sudáfrica', false, default, null, CURRENT_TIMESTAMP, null)
,  (203, 'GS', 'SGS', 'Georgia Sur - Islas Sandwich D', false, default, null, CURRENT_TIMESTAMP, null)
,  (204, 'SS', 'SSD', 'Sudán del Sur', false, default, null, CURRENT_TIMESTAMP, null)
,  (205, 'ES', 'ESP', 'España', false, default, null, CURRENT_TIMESTAMP, null)
,  (206, 'LK', 'LKA', 'Sri lanka', false, default, null, CURRENT_TIMESTAMP, null)
,  (207, 'SD', 'SDN', 'Sudán', false, default, null, CURRENT_TIMESTAMP, null)
,  (208, 'SR', 'SUR', 'Surinam', false, default, null, CURRENT_TIMESTAMP, null)
,  (209, 'SJ', 'SJM', 'Svalbard - Jan Mayen', false, default, null, CURRENT_TIMESTAMP, null)
,  (210, 'SZ', 'SWZ', 'Swazilandia', false, default, null, CURRENT_TIMESTAMP, null)
,  (211, 'SE', 'SWE', 'Suecia', false, default, null, CURRENT_TIMESTAMP, null)
,  (212, 'CH', 'CHE', 'Suiza', false, default, null, CURRENT_TIMESTAMP, null)
,  (213, 'SY', 'SYR', 'Siria', false, default, null, CURRENT_TIMESTAMP, null)
,  (214, 'TW', 'TWN', 'Taiwán', false, default, null, CURRENT_TIMESTAMP, null)
,  (215, 'TJ', 'TJK', 'Tajikistan', false, default, null, CURRENT_TIMESTAMP, null)
,  (216, 'TZ', 'TZA', 'Tanzania', false, default, null, CURRENT_TIMESTAMP, null)
,  (217, 'TH', 'THA', 'Tailandia', false, default, null, CURRENT_TIMESTAMP, null)
,  (218, 'TG', 'TGO', 'Togo', false, default, null, CURRENT_TIMESTAMP, null)
,  (219, 'TK', 'TKL', 'Tokelau', false, default, null, CURRENT_TIMESTAMP, null)
,  (220, 'TO', 'TON', 'Tonga', false, default, null, CURRENT_TIMESTAMP, null)
,  (221, 'TT', 'TTO', 'Trinidad y Tobajo', false, default, null, CURRENT_TIMESTAMP, null)
,  (222, 'TN', 'TUN', 'Tunez', false, default, null, CURRENT_TIMESTAMP, null)
,  (223, 'TR', 'TUR', 'Turquía', false, default, null, CURRENT_TIMESTAMP, null)
,  (224, 'TM', 'TKM', 'Turkmenistán', false, default, null, CURRENT_TIMESTAMP, null)
,  (225, 'TC', 'TCA', 'Turks - Islas Caicos', false, default, null, CURRENT_TIMESTAMP, null)
,  (226, 'TV', 'TUV', 'Tuvalu', false, default, null, CURRENT_TIMESTAMP, null)
,  (227, 'UG', 'UGA', 'Uganda', false, default, null, CURRENT_TIMESTAMP, null)
,  (228, 'UA', 'UKR', 'Ucrania', false, default, null, CURRENT_TIMESTAMP, null)
,  (229, 'AE', 'ARE', 'Emiratos Árabes Unidos', false, default, null, CURRENT_TIMESTAMP, null)
,  (230, 'GB', 'GBR', 'Reino Unido', false, default, null, CURRENT_TIMESTAMP, null)
,  (231, 'US', 'USA', 'Estados Unidos', false, default, null, CURRENT_TIMESTAMP, null)
,  (232, 'UM', 'UMI', 'Islas Menores Y Remotas De Est', false, default, null, CURRENT_TIMESTAMP, null)
,  (233, 'UY', 'URY', 'Uruguay', false, default, null, CURRENT_TIMESTAMP, null)
,  (234, 'UZ', 'UZB', 'Uzbekistán', false, default, null, CURRENT_TIMESTAMP, null)
,  (235, 'VU', 'VUT', 'Vanuatu', false, default, null, CURRENT_TIMESTAMP, null)
,  (236, 'VA', 'VAT', 'Vaticano', false, default, null, CURRENT_TIMESTAMP, null)
,  (237, 'VE', 'VEN', 'Venezuela', false, default, null, CURRENT_TIMESTAMP, null)
,  (238, 'VN', 'VNM', 'Vietnam', false, default, null, CURRENT_TIMESTAMP, null)
,  (239, 'VG', 'VGB', 'Islas Vírgenes (Reino Unido)', false, default, null, CURRENT_TIMESTAMP, null)
,  (240, 'VI', 'VIR', 'Islas Vírgenes (Estados Unidos)', false, default, null, CURRENT_TIMESTAMP, null)
,  (241, 'WF', 'WLF', 'Wallis - Futuna', false, default, null, CURRENT_TIMESTAMP, null)
,  (242, 'EH', 'ESH', 'Sahara Occidental', false, default, null, CURRENT_TIMESTAMP, null)
,  (243, 'YE', 'YEM', 'Yemen', false, default, null, CURRENT_TIMESTAMP, null)
,  (245, 'ZM', 'ZMB', 'Zambia', false, default, null, CURRENT_TIMESTAMP, null)
,  (246, 'ZW', 'ZWE', 'Zimbabwe', false, default, null, CURRENT_TIMESTAMP, null)
,  (247, 'DZ', 'DZA', 'Argelia', false, default, null, CURRENT_TIMESTAMP, null)
,  (248, 'ME', 'MNE', 'Montenegro', false, default, null, CURRENT_TIMESTAMP, null)
,  (249, 'YU', 'YUG', 'Yugoslavia', false, default, null, CURRENT_TIMESTAMP, null)
,  (250, 'NT', 'NTZ', 'Zona Neutral', false, default, null, CURRENT_TIMESTAMP, null)
,  (251, 'CS', 'SCC', 'Serbia And Montenegro', false, default, null, CURRENT_TIMESTAMP, null)
,  (252, 'ZR', 'ZAR', 'Zaire', false, default, null, CURRENT_TIMESTAMP, null)
,  (253, 'BU', 'BUR', 'Burma', false, default, null, CURRENT_TIMESTAMP, null)
,  (254, 'AP', 'APA', 'Apatrida', false, default, null, CURRENT_TIMESTAMP, null)
,  (255, 'CB', 'CBL', 'Colombian Cays', false, default, null, CURRENT_TIMESTAMP, null)
,  (256, 'FX', 'FXX', 'France', false, default, null, CURRENT_TIMESTAMP, null)
,  (257, 'PS', 'PSE', 'Territorio Palestino Ocupado', false, default, null, CURRENT_TIMESTAMP, null)
,  (258, 'VC', 'VCT', 'St Vincent', false, default, null, CURRENT_TIMESTAMP, null)
,  (259, 'NL', 'NLD', 'Holanda', false, default, null, CURRENT_TIMESTAMP, null)
,  (260, 'MD', 'MDA', 'República De Moldova', false, default, null, CURRENT_TIMESTAMP, null)
,  (261, 'SH', 'SHN', 'St Helena', false, default, null, CURRENT_TIMESTAMP, null)
,  (262, 'KN', 'KNA', 'St Kitts - Nevis', false, default, null, CURRENT_TIMESTAMP, null)
;
